/**
 * Lazy loader for the vendored `allw-wasm` core (the only place the SDK touches Rust).
 *
 * All security-critical logic — request-hash canonicalization, JWE encryption, verdict
 * verification — lives once in `allw-core` and is reached here through the WASM surface
 * (`docs/architecture.md`: WASM-local is a hard constraint; no `napi`/native binary). This module
 * only orchestrates loading; it adds no crypto of its own.
 *
 * The vendored `--target web` glue (`packages/sdk/vendor/allw-wasm`, generated by
 * `pnpm run build:wasm` from the repo root and gitignored) is loaded synchronously by compiling
 * the on-disk `.wasm` bytes into a `WebAssembly.Module` and calling `initSync` — one ESM artifact
 * works in both node and the browser/worker. This mirrors `packages/sdk/test/wasm.test.mjs`.
 *
 * @see ../../../docs/architecture.md (WASM-local constraint)
 * @see ../vendor/allw-wasm/allw_wasm.d.ts (the generated FFI surface)
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * The subset of the `allw-wasm` FFI the SDK calls. Every function takes and returns JSON strings
 * (or base64url strings) and **throws** on any error (malformed input, failed verification) —
 * matching the fail-closed invariant at the language boundary (`docs/contract.md` §Invariants #6).
 *
 * This interface is a hand-maintained mirror of the generated `allw_wasm.d.ts` so that the SDK's
 * own types do not depend on the gitignored vendor directory being present at type-check time of
 * downstream consumers; the loader validates the runtime shape against it.
 */
export interface AllwWasm {
  /**
   * Computes the WYSIWYS `request_hash` (base64url-unpadded 32 bytes) for an `ApprovalContext`
   * JSON bound to `expiresAt` (Unix ms). Reproduces the Rust `request-hash/v2` value exactly.
   */
  compute_request_hash(contextJson: string, expiresAt: number): string;
  /**
   * Encrypts an `ApprovalContext` JSON to one or more recipient devices, returning the
   * General-JSON-Serialization JWE string for the envelope's `context_ciphertext`.
   *
   * `recipientsJson` is a JSON array of `{ device_id, public_key_b64 }` (X25519 pubkeys).
   */
  encrypt_context(contextJson: string, recipientsJson: string): string;
  /**
   * Verifies a `Verdict` JSON against the request, the human-shown context, and the approver's
   * account-root Ed25519 public key (base64url). Returns
   * `{ approved: true, device_id, decided_at }` JSON on success; **throws** on any verification
   * failure — including an authenticated non-approval (the message names the verified decision).
   */
  verify_verdict(
    verdictJson: string,
    requestJson: string,
    contextJson: string,
    approverRootPubkeyB64: string,
    nowMs: number,
  ): string;
}

/** The init surface the generated `--target web` glue exposes alongside the FFI functions. */
interface WasmGlue extends AllwWasm {
  initSync(input: { module: WebAssembly.Module }): unknown;
}

/** Resolve the vendored glue directory relative to this compiled module. */
function vendorDir(): string {
  // Compiled to `dist/wasm.js`; the vendor dir is a sibling of `dist` under the package root.
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, "..", "vendor", "allw-wasm");
}

let cached: AllwWasm | null = null;

/**
 * Load (and memoize) the vendored WASM core.
 *
 * @throws if the vendor directory is missing — run `pnpm run build:wasm` from the repo root first.
 */
export async function loadWasm(): Promise<AllwWasm> {
  if (cached) return cached;
  const dir = vendorDir();
  let glue: WasmGlue;
  try {
    // A bare path is not a valid ESM specifier on Windows (`C:\...`); use a file:// URL.
    glue = (await import(pathToFileURL(join(dir, "allw_wasm.js")).href)) as WasmGlue;
    const bytes = readFileSync(join(dir, "allw_wasm_bg.wasm"));
    const module = new WebAssembly.Module(bytes);
    glue.initSync({ module });
  } catch (cause) {
    throw new Error(
      `allw: failed to load the vendored WASM core from ${dir}. ` +
        `Run \`pnpm run build:wasm\` from the repo root first.`,
      { cause },
    );
  }
  cached = glue;
  return cached;
}
