/**
 * Lazy loader for the vendored `allw-wasm` core (the only place the SDK touches Rust).
 *
 * All security-critical logic — request-hash canonicalization, JWE encryption, verdict
 * verification — lives once in `allw-core` and is reached here through the WASM surface
 * (`docs/architecture.md`: WASM-local is a hard constraint; no `napi`/native binary). This module
 * only orchestrates loading; it adds no crypto of its own.
 *
 * The vendored `--target web` glue (`packages/sdk/vendor/allw-wasm`, generated by
 * `pnpm run build:wasm` from the repo root and gitignored) is loaded synchronously by compiling
 * the `.wasm` bytes into a `WebAssembly.Module` and calling `initSync`. **This loader is Node-only**
 * — it reads the bytes from disk via `node:fs`. The same `--target web` artifact is itself
 * browser/worker-capable, but a web host needs a different byte source (e.g. `fetch` + `initSync`);
 * that loader is out of scope here. Mirrors `packages/sdk/test/wasm.test.mjs`.
 *
 * @see ../../../docs/architecture.md (WASM-local constraint)
 * @see ../vendor/allw-wasm/allw_wasm.d.ts (the generated FFI surface)
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * The subset of the `allw-wasm` FFI the SDK calls. Every function takes and returns JSON strings
 * (or base64url strings) and **throws** on any error (malformed input, failed verification) —
 * matching the fail-closed invariant at the language boundary (`docs/contract.md` §Invariants #6).
 *
 * This interface is a hand-maintained mirror of the generated `allw_wasm.d.ts` so that the SDK's
 * own types do not depend on the gitignored vendor directory being present at type-check time of
 * downstream consumers; the loader validates the runtime shape against it.
 */
export interface AllwWasm {
  /**
   * Computes the WYSIWYS `request_hash` (base64url-unpadded 32 bytes) for an `ApprovalContext`
   * JSON bound to `expiresAt` (Unix ms). Reproduces the Rust `request-hash/v2` value exactly.
   */
  compute_request_hash(contextJson: string, expiresAt: number): string;
  /**
   * Encrypts an `ApprovalContext` JSON to one or more recipient devices, returning the
   * General-JSON-Serialization JWE string for the envelope's `context_ciphertext`.
   *
   * `recipientsJson` is a JSON array of `{ device_id, public_key_b64 }` (X25519 pubkeys).
   */
  encrypt_context(contextJson: string, recipientsJson: string): string;
  /**
   * Verifies a `Verdict` JSON against the request, the human-shown context, and the approver's
   * account-root Ed25519 public key (base64url). Returns
   * `{ approved: true, device_id, decided_at, nonce_b64 }` JSON on success; **throws** on any
   * verification failure — including an authenticated non-approval (the message names the verified
   * decision).
   */
  verify_verdict(
    verdictJson: string,
    requestJson: string,
    contextJson: string,
    approverRootPubkeyB64: string,
    nowMs: number,
    expectedAccountId?: string | null,
  ): string;
  /**
   * Verifies a verdict and rejects it when the signing device appears revoked in the
   * highest-sequence valid account state. `accountStatesJson` is a JSON array of compact
   * root-signed account-state JWS strings.
   */
  verify_verdict_with_account_states(
    verdictJson: string,
    requestJson: string,
    contextJson: string,
    approverRootPubkeyB64: string,
    nowMs: number,
    accountStatesJson: string,
    expectedAccountId?: string | null,
  ): string;
  /** Sign a root-authored account-state JSON document, returning a compact account-state JWS. */
  sign_account_state(stateJson: string, accountRootSeedB64: string): string;
  /** Verify a compact account-state JWS and return the verified AccountState JSON. */
  verify_account_state(
    accountStateJws: string,
    expectedAccountId: string,
    accountRootPubkeyB64: string,
  ): string;
  /**
   * Resolves the device ids revoked in the highest-sequence valid account state(s), returning a
   * JSON array of device id strings (empty when `accountStatesJson` is `"[]"`). Used to filter
   * revoked devices out of the JWE recipient set **before** encrypting a new request (issue #204
   * fix 1) — the parse/verify/resolve logic stays in core; the caller only drops matching ids.
   */
  revoked_device_ids(
    accountStatesJson: string,
    expectedAccountId: string,
    accountRootPubkeyB64: string,
  ): string;
  /** Derive the Ed25519 public key for a 32-byte signing seed (base64url). */
  ed25519_public_key(seedB64: string): string;
  /** Build an ActionRecord JSON for a shell command using the core T1 command parser. */
  action_from_command(commandLine: string, cwd?: string | null): string;
  /** Sign an unsigned PolicyRule JSON with a device key and cert, returning signed JSON. */
  sign_policy_rule(
    unsignedRuleJson: string,
    deviceId: string,
    deviceSeedB64: string,
    deviceCert: string,
  ): string;
  /**
   * Emit a signed allow PolicyRule from an approved action plus syntactic scope choice.
   * `scopeJson` is a PolicyRuleScope JSON value such as `{ "kind": "exact_call" }`.
   */
  policy_rule_from_approval(
    id: string,
    accountId: string,
    actorJson: string,
    actionJson: string,
    scopeJson: string,
    createdAt: number,
    deviceId: string,
    deviceSeedB64: string,
    deviceCert: string,
  ): string;
  /** Verify signed PolicyRule JSON objects and evaluate them against one ActionRecord JSON. */
  evaluate_policy(
    actionJson: string,
    actorJson: string | null | undefined,
    signedRulesJson: string,
    accountRootPubkeyB64: string,
    nowMs: number,
    expectedAccountId?: string | null,
  ): string;
  /** Verify one signed PolicyRule JSON object with account-state revocation enforcement. */
  verify_policy_rule_with_account_states(
    ruleJson: string,
    accountRootPubkeyB64: string,
    nowMs: number,
    accountStatesJson: string,
    expectedAccountId?: string | null,
  ): string;
  /** Verify signed PolicyRule JSON objects with account-state revocation and evaluate one action. */
  evaluate_policy_with_account_states(
    actionJson: string,
    actorJson: string | null | undefined,
    signedRulesJson: string,
    accountRootPubkeyB64: string,
    nowMs: number,
    accountStatesJson: string,
    expectedAccountId?: string | null,
  ): string;
}

/** The init surface the generated `--target web` glue exposes alongside the FFI functions. */
interface WasmGlue extends AllwWasm {
  initSync(input: { module: WebAssembly.Module }): unknown;
}

/** Resolve the vendored glue directory relative to this compiled module. */
function vendorDir(): string {
  // Compiled to `dist/wasm.js`; the vendor dir is a sibling of `dist` under the package root.
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, "..", "vendor", "allw-wasm");
}

let cached: AllwWasm | null = null;

/**
 * Load (and memoize) the vendored WASM core.
 *
 * @throws if the vendor directory is missing — run `pnpm run build:wasm` from the repo root first.
 */
export async function loadWasm(): Promise<AllwWasm> {
  if (cached) return cached;
  const dir = vendorDir();
  let glue: WasmGlue;
  try {
    // A bare path is not a valid ESM specifier on Windows (`C:\...`); use a file:// URL.
    glue = (await import(pathToFileURL(join(dir, "allw_wasm.js")).href)) as WasmGlue;
    const bytes = readFileSync(join(dir, "allw_wasm_bg.wasm"));
    const module = new WebAssembly.Module(bytes);
    glue.initSync({ module });
  } catch (cause) {
    throw new Error(
      `allw: failed to load the vendored WASM core from ${dir}. ` +
        `Run \`pnpm run build:wasm\` from the repo root first.`,
      { cause },
    );
  }
  cached = glue;
  return cached;
}
